### ISSUE TITLE
update file

### ISSUE THREAD

**Issue by xenoterracide** [xenoterracide/brix#1]
hygen has `before` and `after` but you could do something more simple with just a regex, with a capture group, that can match newlines. given a project that has this file, `settings.gradle.kts`

```kts
rootProject.name = "ppm-backend"

include(
  ":app",
  ":authn"
)
```

```yml
workdir:
templates:
  settings.gradle.kts:
    destination: '{{name}}/settings.gradle.kts'
    pattern: '^(include\($)' # I don't think this is actually valid for a multiline match
    replace: '$1  :"{{moduleType}}",'
    context:
      project: ''
```

on `brix java module foo` the `settings.gradle.kts` would be changed to be

```kts
rootProject.name = "ppm-backend"

include(
  ":foo",
  ":app",
  ":authn"
)
````
