### ISSUE TITLE
search/replace

### ISSUE THREAD

**Issue by xenoterracide** [xenoterracide/brix#10]
tempted to name the command `sed` because what I'm thinking of is referred to as a sed patch.

note: I'm not sure of the exact invocation for a platform-agnostic line ending in rust

```yml
commands:
- search_replace:
    dest: settings.gradle.kts
    search: '^include\($'
    replace: '%n":{{foo}}"%n,'
    context:
       foo: bar
```

which would allow

```kts
include(
  ":app",
)
```
to then become

```kts
include(
  ":bar",
  ":app",
)
```
