### ISSUE TITLE
mkdir

### ISSUE THREAD

**Issue by xenoterracide** [xenoterracide/brix#11]
equivalent to unix `mkdir -p`
```yml
commands:
- mkdir:
    dest: {{name}}/src/main/java/com/xenoterracide/{{project}}/{{foo}}
    context:
        foo: bar
```
