### ISSUE TITLE
Template files

### ISSUE THREAD

**Issue by xenoterracide** [xenoterracide/brix#9]
Not certain we need to support multiple engines, so let's not worry about it

```yml
commands:
- template:
    src: template.ext.tmpl
    dest: module/{{foo}}/my.ext
    braces: # probably shouldn't impact the config file
    context:
       foo: bar
  ```
